#!/usr/bin/env python3
# Copyright 2025 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
# Author: Jiacong Sun <jiacong.sun@kuleuven.be>
#
# Converts the state output files of core n (states_out_<2n+1> and states_out_<2n+2>) into a C
# header holding the spin vectors the analog macro returns, so that a test can compare against
# them.
#
# The behaviour model of the macro (hw/tb/models/galena/galena_pkg.sv) interleaves the two files
# into one spin cache memory, taking states_out_<2n+1> for the even entries and states_out_<2n+2>
# for the odd ones, and hands out one entry per spin write. This script reproduces that order.
#
# Output: sw/include/gen/state_out_ref.h
#   - state_out_ref[STATE_OUT_REF_NUM][4] : spin vectors as 4 x uint64_t, entry i being the vector
#                                           returned after the (i+1)-th spin write
#
# Bit ordering per vector:
#   last char of line  -> bit 0   of word[0]
#   first char of line -> bit 63  of word[3]

import argparse
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SW_DIR = os.path.join(SCRIPT_DIR, "..")

VEC_BITS = 256
WORDS_PER_VEC = VEC_BITS // 64  # 4 x uint64_t per vector


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate sw/include/state_out_ref.h from the state output files of one core."
    )
    parser.add_argument(
        "--core-onload",
        type=int,
        default=0,
        help="Index of the core this data belongs to, selecting "
             "states_out_<2n+1>/<2n+2> (default: 0).",
    )
    parser.add_argument(
        "--folder",
        type=str,
        default="default",
        help="Folder name under sw/tests/data/ containing the state output files",
    )
    parser.add_argument(
        "--suffix",
        type=str,
        default="",
        help="Output name suffix (default: "").",
    )
    parser.add_argument(
        "--num",
        type=int,
        default=8,
        help="Number of interleaved spin vectors to emit (default: 8).",
    )
    return parser.parse_args()


args = parse_args()
OUTPUT_FILE = os.path.join(SW_DIR, "include", "gen", f"state_out_ref{args.suffix}.h")
os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
# Core n is loaded with states_out_(2n+1) and states_out_(2n+2): core 0 -> 1/2, core 1 -> 3/4.
INPUT_NAME_1 = f"states_out_{2 * args.core_onload + 1}"
INPUT_NAME_2 = f"states_out_{2 * args.core_onload + 2}"
INPUT_FILE_1 = os.path.join(SW_DIR, "tests/data", args.folder, INPUT_NAME_1)
INPUT_FILE_2 = os.path.join(SW_DIR, "tests/data", args.folder, INPUT_NAME_2)


def parse_state_file(path):
    """Return the state vectors of one file, the first line being a header."""
    with open(path, 'r') as f:
        lines = [line.strip() for line in f if line.strip() and not line.startswith("#")]
    assert len(lines) >= 2, f"{path}: expected a header line and at least one state"
    vecs = []
    for n, line in enumerate(lines[1:]):
        # The model keeps the 0/1 characters of a line and ignores everything else
        bits = "".join(c for c in line if c in "01")
        assert len(bits) == VEC_BITS, \
            f"{path} line {n + 2}: expected {VEC_BITS} bits, got {len(bits)}"
        vecs.append(bits)
    return vecs


vecs_1 = parse_state_file(INPUT_FILE_1)
vecs_2 = parse_state_file(INPUT_FILE_2)

# Interleave the way the macro model fills its spin cache: [f1[0], f2[0], f1[1], f2[1], ...]
interleaved = []
for i in range(min(len(vecs_1), len(vecs_2))):
    interleaved.append(vecs_1[i])
    interleaved.append(vecs_2[i])

assert len(interleaved) >= args.num, \
    f"{INPUT_FILE_1} and {INPUT_FILE_2} hold {len(interleaved)} states, {args.num} requested"
interleaved = interleaved[:args.num]


def pack(bits):
    """Pack a 256-char binary string into 4 x uint64_t, last char first."""
    value = int(bits, 2)
    return [(value >> (64 * k)) & 0xFFFFFFFFFFFFFFFF for k in range(WORDS_PER_VEC)]


with open(OUTPUT_FILE, 'w') as f:
    f.write("// Auto-generated by gen_state_out_ref.py - do not edit\n")
    f.write(f"// Sources: sw/tests/data/{args.folder}/{INPUT_NAME_1}, {INPUT_NAME_2}\n")
    f.write("// Copyright 2025 KU Leuven.\n")
    f.write("// Licensed under the Apache License, Version 2.0, see LICENSE for details.\n")
    f.write("// SPDX-License-Identifier: Apache-2.0\n")
    f.write("\n")
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n")
    f.write("\n")
    f.write("// Spin vectors returned by the analog macro, one per spin write, interleaved from\n")
    f.write(f"// {INPUT_NAME_1} (even entries) and {INPUT_NAME_2} (odd entries).\n")
    f.write("// word[0] holds bits  63:0   (last  64 chars of the source line)\n")
    f.write("// word[3] holds bits 255:192 (first 64 chars of the source line)\n")
    f.write(f"#define STATE_OUT_REF_NUM {args.num}\n")
    f.write(f"static const uint64_t state_out_ref{args.suffix}"
            f"[STATE_OUT_REF_NUM][{WORDS_PER_VEC}] = {{\n")
    for i, bits in enumerate(interleaved):
        words = ", ".join(f"0x{w:016x}ULL" for w in pack(bits))
        src = INPUT_NAME_1 if i % 2 == 0 else INPUT_NAME_2
        f.write(f"    {{{words}}}, // spin write {i}, {src} state {i // 2}\n")
    f.write("};\n")

print(f"Generated {OUTPUT_FILE}")
print(f"  {args.num} spin vectors interleaved from {INPUT_NAME_1} and {INPUT_NAME_2}")
print(f"  first vector: {['0x%016x' % w for w in pack(interleaved[0])]}")
