# Copyright 2025 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Giuseppe Sarda <giuseppe.sarda@esat.kuleuven.be>

verible.filelist:
	find . -name "*.sv" -o -name "*.svh" -o -name "*.v" -o -name "*.vh" | sort > ./tools/lint/verible/verible.filelist