# Copyright 2025 KU Leuven.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
#
# Author: Giuseppe Sarda <giuseppe.sarda@esat.kuleuven.be>

verible.filelist:
	find . -name "*.sv" -o -name "*.svh" -o -name "*.v" -o -name "*.vh" | sort > ./tools/lint/verible/verible.filelist