// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package lagd_core_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 10;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } flush_en;
    struct packed {
      logic        q;
    } en_aw;
    struct packed {
      logic        q;
    } en_em;
    struct packed {
      logic        q;
    } en_fm;
    struct packed {
      logic        q;
    } en_ff;
    struct packed {
      logic        q;
    } en_ef;
    struct packed {
      logic        q;
    } en_analog_loop;
    struct packed {
      logic        q;
    } en_comparison;
    struct packed {
      logic        q;
    } cmpt_en;
    struct packed {
      logic        q;
    } config_valid_aw;
    struct packed {
      logic        q;
    } config_valid_em;
    struct packed {
      logic        q;
    } config_valid_fm;
    struct packed {
      logic        q;
    } debug_dt_configure_enable;
    struct packed {
      logic        q;
    } debug_spin_configure_enable;
    struct packed {
      logic        q;
    } config_spin_initial_skip;
    struct packed {
      logic        q;
    } bypass_data_conversion;
    struct packed {
      logic        q;
    } dt_cfg_enable;
    struct packed {
      logic        q;
    } host_readout;
    struct packed {
      logic        q;
    } flip_disable;
    struct packed {
      logic        q;
    } enable_flip_detection;
    struct packed {
      logic        q;
    } debug_j_write_en;
    struct packed {
      logic        q;
    } debug_j_read_en;
    struct packed {
      logic        q;
    } debug_spin_write_en;
    struct packed {
      logic        q;
    } debug_spin_compute_en;
    struct packed {
      logic        q;
    } debug_spin_read_en;
    struct packed {
      logic [7:0]  q;
    } config_counter;
    struct packed {
      logic        q;
    } wwl_vdd_cfg_256;
    struct packed {
      logic        q;
    } wwl_vread_cfg_256;
    struct packed {
      logic [1:0]  q;
    } synchronizer_pipe_num;
    struct packed {
      logic [1:0]  q;
    } synchronizer_wbl_pipe_num;
    struct packed {
      logic        q;
    } debug_h_wwl;
    struct packed {
      logic [5:0]  q;
    } dgt_addr_upper_bound;
    struct packed {
      logic        q;
    } ctnus_fifo_read;
  } lagd_core_reg2hw_global_cfg_reg_t;

  typedef struct packed {
    logic [63:0] q;
  } lagd_core_reg2hw_config_spin_initial_mreg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } cfg_trans_num;
    struct packed {
      logic [15:0] q;
    } cycle_per_wwl_high;
    struct packed {
      logic [15:0] q;
    } cycle_per_wwl_low;
    struct packed {
      logic [15:0] q;
    } cycle_per_spin_write;
  } lagd_core_reg2hw_counter_cfg_1_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } cycle_per_spin_compute;
    struct packed {
      logic [15:0] q;
    } debug_cycle_per_spin_read;
    struct packed {
      logic [15:0] q;
    } debug_spin_read_num;
    struct packed {
      logic [10:0] q;
    } icon_last_raddr_plus_one;
    struct packed {
      logic [4:0]  q;
    } dgt_hscaling;
  } lagd_core_reg2hw_counter_cfg_2_reg_t;

  typedef struct packed {
    logic [63:0] q;
  } lagd_core_reg2hw_wwl_vdd_cfg_mreg_t;

  typedef struct packed {
    logic [63:0] q;
  } lagd_core_reg2hw_wwl_vread_cfg_mreg_t;

  typedef struct packed {
    logic [63:0] q;
  } lagd_core_reg2hw_spin_wwl_strobe_mreg_t;

  typedef struct packed {
    logic [63:0] q;
  } lagd_core_reg2hw_spin_feedback_cfg_mreg_t;

  typedef struct packed {
    logic [63:0] q;
  } lagd_core_reg2hw_h_rdata_mreg_t;

  typedef struct packed {
    logic [63:0] q;
  } lagd_core_reg2hw_wbl_floating_mreg_t;

  typedef struct packed {
    logic [63:0] q;
  } lagd_core_reg2hw_debug_j_one_hot_wwl_mreg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } dt_cfg_idle;
    struct packed {
      logic        d;
      logic        de;
    } cmpt_idle;
    struct packed {
      logic        d;
      logic        de;
    } energy_fifo_update;
    struct packed {
      logic        d;
      logic        de;
    } spin_fifo_update;
    struct packed {
      logic        d;
      logic        de;
    } debug_j_read_data_valid;
    struct packed {
      logic        d;
      logic        de;
    } debug_analog_dt_w_idle;
    struct packed {
      logic        d;
      logic        de;
    } debug_analog_dt_r_idle;
    struct packed {
      logic        d;
      logic        de;
    } debug_spin_w_idle;
    struct packed {
      logic        d;
      logic        de;
    } debug_spin_r_idle;
    struct packed {
      logic        d;
      logic        de;
    } debug_spin_cmpt_idle;
  } lagd_core_hw2reg_output_status_reg_t;

  typedef struct packed {
    struct packed {
      logic [31:0] d;
      logic        de;
    } energy_fifo_0;
    struct packed {
      logic [31:0] d;
      logic        de;
    } energy_fifo_1;
  } lagd_core_hw2reg_energy_fifo_data_reg_t;

  typedef struct packed {
    logic [63:0] d;
    logic        de;
  } lagd_core_hw2reg_spin_fifo_data_0_mreg_t;

  typedef struct packed {
    logic [63:0] d;
    logic        de;
  } lagd_core_hw2reg_spin_fifo_data_1_mreg_t;

  typedef struct packed {
    logic [63:0] d;
    logic        de;
  } lagd_core_hw2reg_debug_j_read_data_mreg_t;

  // Register -> HW type
  typedef struct packed {
    lagd_core_reg2hw_global_cfg_reg_t global_cfg; // [3758:3712]
    lagd_core_reg2hw_config_spin_initial_mreg_t [3:0] config_spin_initial; // [3711:3456]
    lagd_core_reg2hw_counter_cfg_1_reg_t counter_cfg_1; // [3455:3392]
    lagd_core_reg2hw_counter_cfg_2_reg_t counter_cfg_2; // [3391:3328]
    lagd_core_reg2hw_wwl_vdd_cfg_mreg_t [3:0] wwl_vdd_cfg; // [3327:3072]
    lagd_core_reg2hw_wwl_vread_cfg_mreg_t [3:0] wwl_vread_cfg; // [3071:2816]
    lagd_core_reg2hw_spin_wwl_strobe_mreg_t [3:0] spin_wwl_strobe; // [2815:2560]
    lagd_core_reg2hw_spin_feedback_cfg_mreg_t [3:0] spin_feedback_cfg; // [2559:2304]
    lagd_core_reg2hw_h_rdata_mreg_t [15:0] h_rdata; // [2303:1280]
    lagd_core_reg2hw_wbl_floating_mreg_t [15:0] wbl_floating; // [1279:256]
    lagd_core_reg2hw_debug_j_one_hot_wwl_mreg_t [3:0] debug_j_one_hot_wwl; // [255:0]
  } lagd_core_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    lagd_core_hw2reg_output_status_reg_t output_status; // [1645:1626]
    lagd_core_hw2reg_energy_fifo_data_reg_t energy_fifo_data; // [1625:1560]
    lagd_core_hw2reg_spin_fifo_data_0_mreg_t [3:0] spin_fifo_data_0; // [1559:1300]
    lagd_core_hw2reg_spin_fifo_data_1_mreg_t [3:0] spin_fifo_data_1; // [1299:1040]
    lagd_core_hw2reg_debug_j_read_data_mreg_t [15:0] debug_j_read_data; // [1039:0]
  } lagd_core_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] LAGD_CORE_GLOBAL_CFG_OFFSET = 10'h 0;
  parameter logic [BlockAw-1:0] LAGD_CORE_CONFIG_SPIN_INITIAL_0_OFFSET = 10'h 8;
  parameter logic [BlockAw-1:0] LAGD_CORE_CONFIG_SPIN_INITIAL_1_OFFSET = 10'h 10;
  parameter logic [BlockAw-1:0] LAGD_CORE_CONFIG_SPIN_INITIAL_2_OFFSET = 10'h 18;
  parameter logic [BlockAw-1:0] LAGD_CORE_CONFIG_SPIN_INITIAL_3_OFFSET = 10'h 20;
  parameter logic [BlockAw-1:0] LAGD_CORE_COUNTER_CFG_1_OFFSET = 10'h 28;
  parameter logic [BlockAw-1:0] LAGD_CORE_COUNTER_CFG_2_OFFSET = 10'h 30;
  parameter logic [BlockAw-1:0] LAGD_CORE_WWL_VDD_CFG_0_OFFSET = 10'h 38;
  parameter logic [BlockAw-1:0] LAGD_CORE_WWL_VDD_CFG_1_OFFSET = 10'h 40;
  parameter logic [BlockAw-1:0] LAGD_CORE_WWL_VDD_CFG_2_OFFSET = 10'h 48;
  parameter logic [BlockAw-1:0] LAGD_CORE_WWL_VDD_CFG_3_OFFSET = 10'h 50;
  parameter logic [BlockAw-1:0] LAGD_CORE_WWL_VREAD_CFG_0_OFFSET = 10'h 58;
  parameter logic [BlockAw-1:0] LAGD_CORE_WWL_VREAD_CFG_1_OFFSET = 10'h 60;
  parameter logic [BlockAw-1:0] LAGD_CORE_WWL_VREAD_CFG_2_OFFSET = 10'h 68;
  parameter logic [BlockAw-1:0] LAGD_CORE_WWL_VREAD_CFG_3_OFFSET = 10'h 70;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_WWL_STROBE_0_OFFSET = 10'h 78;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_WWL_STROBE_1_OFFSET = 10'h 80;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_WWL_STROBE_2_OFFSET = 10'h 88;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_WWL_STROBE_3_OFFSET = 10'h 90;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FEEDBACK_CFG_0_OFFSET = 10'h 98;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FEEDBACK_CFG_1_OFFSET = 10'h a0;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FEEDBACK_CFG_2_OFFSET = 10'h a8;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FEEDBACK_CFG_3_OFFSET = 10'h b0;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_0_OFFSET = 10'h b8;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_1_OFFSET = 10'h c0;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_2_OFFSET = 10'h c8;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_3_OFFSET = 10'h d0;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_4_OFFSET = 10'h d8;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_5_OFFSET = 10'h e0;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_6_OFFSET = 10'h e8;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_7_OFFSET = 10'h f0;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_8_OFFSET = 10'h f8;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_9_OFFSET = 10'h 100;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_10_OFFSET = 10'h 108;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_11_OFFSET = 10'h 110;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_12_OFFSET = 10'h 118;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_13_OFFSET = 10'h 120;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_14_OFFSET = 10'h 128;
  parameter logic [BlockAw-1:0] LAGD_CORE_H_RDATA_15_OFFSET = 10'h 130;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_0_OFFSET = 10'h 138;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_1_OFFSET = 10'h 140;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_2_OFFSET = 10'h 148;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_3_OFFSET = 10'h 150;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_4_OFFSET = 10'h 158;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_5_OFFSET = 10'h 160;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_6_OFFSET = 10'h 168;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_7_OFFSET = 10'h 170;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_8_OFFSET = 10'h 178;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_9_OFFSET = 10'h 180;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_10_OFFSET = 10'h 188;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_11_OFFSET = 10'h 190;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_12_OFFSET = 10'h 198;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_13_OFFSET = 10'h 1a0;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_14_OFFSET = 10'h 1a8;
  parameter logic [BlockAw-1:0] LAGD_CORE_WBL_FLOATING_15_OFFSET = 10'h 1b0;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_ONE_HOT_WWL_0_OFFSET = 10'h 1b8;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_ONE_HOT_WWL_1_OFFSET = 10'h 1c0;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_ONE_HOT_WWL_2_OFFSET = 10'h 1c8;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_ONE_HOT_WWL_3_OFFSET = 10'h 1d0;
  parameter logic [BlockAw-1:0] LAGD_CORE_OUTPUT_STATUS_OFFSET = 10'h 1d8;
  parameter logic [BlockAw-1:0] LAGD_CORE_ENERGY_FIFO_DATA_OFFSET = 10'h 1e0;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FIFO_DATA_0_0_OFFSET = 10'h 1e8;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FIFO_DATA_0_1_OFFSET = 10'h 1f0;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FIFO_DATA_0_2_OFFSET = 10'h 1f8;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FIFO_DATA_0_3_OFFSET = 10'h 200;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FIFO_DATA_1_0_OFFSET = 10'h 208;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FIFO_DATA_1_1_OFFSET = 10'h 210;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FIFO_DATA_1_2_OFFSET = 10'h 218;
  parameter logic [BlockAw-1:0] LAGD_CORE_SPIN_FIFO_DATA_1_3_OFFSET = 10'h 220;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_0_OFFSET = 10'h 228;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_1_OFFSET = 10'h 230;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_2_OFFSET = 10'h 238;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_3_OFFSET = 10'h 240;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_4_OFFSET = 10'h 248;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_5_OFFSET = 10'h 250;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_6_OFFSET = 10'h 258;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_7_OFFSET = 10'h 260;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_8_OFFSET = 10'h 268;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_9_OFFSET = 10'h 270;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_10_OFFSET = 10'h 278;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_11_OFFSET = 10'h 280;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_12_OFFSET = 10'h 288;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_13_OFFSET = 10'h 290;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_14_OFFSET = 10'h 298;
  parameter logic [BlockAw-1:0] LAGD_CORE_DEBUG_J_READ_DATA_15_OFFSET = 10'h 2a0;

  // Register index
  typedef enum int {
    LAGD_CORE_GLOBAL_CFG,
    LAGD_CORE_CONFIG_SPIN_INITIAL_0,
    LAGD_CORE_CONFIG_SPIN_INITIAL_1,
    LAGD_CORE_CONFIG_SPIN_INITIAL_2,
    LAGD_CORE_CONFIG_SPIN_INITIAL_3,
    LAGD_CORE_COUNTER_CFG_1,
    LAGD_CORE_COUNTER_CFG_2,
    LAGD_CORE_WWL_VDD_CFG_0,
    LAGD_CORE_WWL_VDD_CFG_1,
    LAGD_CORE_WWL_VDD_CFG_2,
    LAGD_CORE_WWL_VDD_CFG_3,
    LAGD_CORE_WWL_VREAD_CFG_0,
    LAGD_CORE_WWL_VREAD_CFG_1,
    LAGD_CORE_WWL_VREAD_CFG_2,
    LAGD_CORE_WWL_VREAD_CFG_3,
    LAGD_CORE_SPIN_WWL_STROBE_0,
    LAGD_CORE_SPIN_WWL_STROBE_1,
    LAGD_CORE_SPIN_WWL_STROBE_2,
    LAGD_CORE_SPIN_WWL_STROBE_3,
    LAGD_CORE_SPIN_FEEDBACK_CFG_0,
    LAGD_CORE_SPIN_FEEDBACK_CFG_1,
    LAGD_CORE_SPIN_FEEDBACK_CFG_2,
    LAGD_CORE_SPIN_FEEDBACK_CFG_3,
    LAGD_CORE_H_RDATA_0,
    LAGD_CORE_H_RDATA_1,
    LAGD_CORE_H_RDATA_2,
    LAGD_CORE_H_RDATA_3,
    LAGD_CORE_H_RDATA_4,
    LAGD_CORE_H_RDATA_5,
    LAGD_CORE_H_RDATA_6,
    LAGD_CORE_H_RDATA_7,
    LAGD_CORE_H_RDATA_8,
    LAGD_CORE_H_RDATA_9,
    LAGD_CORE_H_RDATA_10,
    LAGD_CORE_H_RDATA_11,
    LAGD_CORE_H_RDATA_12,
    LAGD_CORE_H_RDATA_13,
    LAGD_CORE_H_RDATA_14,
    LAGD_CORE_H_RDATA_15,
    LAGD_CORE_WBL_FLOATING_0,
    LAGD_CORE_WBL_FLOATING_1,
    LAGD_CORE_WBL_FLOATING_2,
    LAGD_CORE_WBL_FLOATING_3,
    LAGD_CORE_WBL_FLOATING_4,
    LAGD_CORE_WBL_FLOATING_5,
    LAGD_CORE_WBL_FLOATING_6,
    LAGD_CORE_WBL_FLOATING_7,
    LAGD_CORE_WBL_FLOATING_8,
    LAGD_CORE_WBL_FLOATING_9,
    LAGD_CORE_WBL_FLOATING_10,
    LAGD_CORE_WBL_FLOATING_11,
    LAGD_CORE_WBL_FLOATING_12,
    LAGD_CORE_WBL_FLOATING_13,
    LAGD_CORE_WBL_FLOATING_14,
    LAGD_CORE_WBL_FLOATING_15,
    LAGD_CORE_DEBUG_J_ONE_HOT_WWL_0,
    LAGD_CORE_DEBUG_J_ONE_HOT_WWL_1,
    LAGD_CORE_DEBUG_J_ONE_HOT_WWL_2,
    LAGD_CORE_DEBUG_J_ONE_HOT_WWL_3,
    LAGD_CORE_OUTPUT_STATUS,
    LAGD_CORE_ENERGY_FIFO_DATA,
    LAGD_CORE_SPIN_FIFO_DATA_0_0,
    LAGD_CORE_SPIN_FIFO_DATA_0_1,
    LAGD_CORE_SPIN_FIFO_DATA_0_2,
    LAGD_CORE_SPIN_FIFO_DATA_0_3,
    LAGD_CORE_SPIN_FIFO_DATA_1_0,
    LAGD_CORE_SPIN_FIFO_DATA_1_1,
    LAGD_CORE_SPIN_FIFO_DATA_1_2,
    LAGD_CORE_SPIN_FIFO_DATA_1_3,
    LAGD_CORE_DEBUG_J_READ_DATA_0,
    LAGD_CORE_DEBUG_J_READ_DATA_1,
    LAGD_CORE_DEBUG_J_READ_DATA_2,
    LAGD_CORE_DEBUG_J_READ_DATA_3,
    LAGD_CORE_DEBUG_J_READ_DATA_4,
    LAGD_CORE_DEBUG_J_READ_DATA_5,
    LAGD_CORE_DEBUG_J_READ_DATA_6,
    LAGD_CORE_DEBUG_J_READ_DATA_7,
    LAGD_CORE_DEBUG_J_READ_DATA_8,
    LAGD_CORE_DEBUG_J_READ_DATA_9,
    LAGD_CORE_DEBUG_J_READ_DATA_10,
    LAGD_CORE_DEBUG_J_READ_DATA_11,
    LAGD_CORE_DEBUG_J_READ_DATA_12,
    LAGD_CORE_DEBUG_J_READ_DATA_13,
    LAGD_CORE_DEBUG_J_READ_DATA_14,
    LAGD_CORE_DEBUG_J_READ_DATA_15
  } lagd_core_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] LAGD_CORE_PERMIT [85] = '{
    4'b 1111, // index[ 0] LAGD_CORE_GLOBAL_CFG
    4'b 1111, // index[ 1] LAGD_CORE_CONFIG_SPIN_INITIAL_0
    4'b 1111, // index[ 2] LAGD_CORE_CONFIG_SPIN_INITIAL_1
    4'b 1111, // index[ 3] LAGD_CORE_CONFIG_SPIN_INITIAL_2
    4'b 1111, // index[ 4] LAGD_CORE_CONFIG_SPIN_INITIAL_3
    4'b 1111, // index[ 5] LAGD_CORE_COUNTER_CFG_1
    4'b 1111, // index[ 6] LAGD_CORE_COUNTER_CFG_2
    4'b 1111, // index[ 7] LAGD_CORE_WWL_VDD_CFG_0
    4'b 1111, // index[ 8] LAGD_CORE_WWL_VDD_CFG_1
    4'b 1111, // index[ 9] LAGD_CORE_WWL_VDD_CFG_2
    4'b 1111, // index[10] LAGD_CORE_WWL_VDD_CFG_3
    4'b 1111, // index[11] LAGD_CORE_WWL_VREAD_CFG_0
    4'b 1111, // index[12] LAGD_CORE_WWL_VREAD_CFG_1
    4'b 1111, // index[13] LAGD_CORE_WWL_VREAD_CFG_2
    4'b 1111, // index[14] LAGD_CORE_WWL_VREAD_CFG_3
    4'b 1111, // index[15] LAGD_CORE_SPIN_WWL_STROBE_0
    4'b 1111, // index[16] LAGD_CORE_SPIN_WWL_STROBE_1
    4'b 1111, // index[17] LAGD_CORE_SPIN_WWL_STROBE_2
    4'b 1111, // index[18] LAGD_CORE_SPIN_WWL_STROBE_3
    4'b 1111, // index[19] LAGD_CORE_SPIN_FEEDBACK_CFG_0
    4'b 1111, // index[20] LAGD_CORE_SPIN_FEEDBACK_CFG_1
    4'b 1111, // index[21] LAGD_CORE_SPIN_FEEDBACK_CFG_2
    4'b 1111, // index[22] LAGD_CORE_SPIN_FEEDBACK_CFG_3
    4'b 1111, // index[23] LAGD_CORE_H_RDATA_0
    4'b 1111, // index[24] LAGD_CORE_H_RDATA_1
    4'b 1111, // index[25] LAGD_CORE_H_RDATA_2
    4'b 1111, // index[26] LAGD_CORE_H_RDATA_3
    4'b 1111, // index[27] LAGD_CORE_H_RDATA_4
    4'b 1111, // index[28] LAGD_CORE_H_RDATA_5
    4'b 1111, // index[29] LAGD_CORE_H_RDATA_6
    4'b 1111, // index[30] LAGD_CORE_H_RDATA_7
    4'b 1111, // index[31] LAGD_CORE_H_RDATA_8
    4'b 1111, // index[32] LAGD_CORE_H_RDATA_9
    4'b 1111, // index[33] LAGD_CORE_H_RDATA_10
    4'b 1111, // index[34] LAGD_CORE_H_RDATA_11
    4'b 1111, // index[35] LAGD_CORE_H_RDATA_12
    4'b 1111, // index[36] LAGD_CORE_H_RDATA_13
    4'b 1111, // index[37] LAGD_CORE_H_RDATA_14
    4'b 1111, // index[38] LAGD_CORE_H_RDATA_15
    4'b 1111, // index[39] LAGD_CORE_WBL_FLOATING_0
    4'b 1111, // index[40] LAGD_CORE_WBL_FLOATING_1
    4'b 1111, // index[41] LAGD_CORE_WBL_FLOATING_2
    4'b 1111, // index[42] LAGD_CORE_WBL_FLOATING_3
    4'b 1111, // index[43] LAGD_CORE_WBL_FLOATING_4
    4'b 1111, // index[44] LAGD_CORE_WBL_FLOATING_5
    4'b 1111, // index[45] LAGD_CORE_WBL_FLOATING_6
    4'b 1111, // index[46] LAGD_CORE_WBL_FLOATING_7
    4'b 1111, // index[47] LAGD_CORE_WBL_FLOATING_8
    4'b 1111, // index[48] LAGD_CORE_WBL_FLOATING_9
    4'b 1111, // index[49] LAGD_CORE_WBL_FLOATING_10
    4'b 1111, // index[50] LAGD_CORE_WBL_FLOATING_11
    4'b 1111, // index[51] LAGD_CORE_WBL_FLOATING_12
    4'b 1111, // index[52] LAGD_CORE_WBL_FLOATING_13
    4'b 1111, // index[53] LAGD_CORE_WBL_FLOATING_14
    4'b 1111, // index[54] LAGD_CORE_WBL_FLOATING_15
    4'b 1111, // index[55] LAGD_CORE_DEBUG_J_ONE_HOT_WWL_0
    4'b 1111, // index[56] LAGD_CORE_DEBUG_J_ONE_HOT_WWL_1
    4'b 1111, // index[57] LAGD_CORE_DEBUG_J_ONE_HOT_WWL_2
    4'b 1111, // index[58] LAGD_CORE_DEBUG_J_ONE_HOT_WWL_3
    4'b 0011, // index[59] LAGD_CORE_OUTPUT_STATUS
    4'b 1111, // index[60] LAGD_CORE_ENERGY_FIFO_DATA
    4'b 1111, // index[61] LAGD_CORE_SPIN_FIFO_DATA_0_0
    4'b 1111, // index[62] LAGD_CORE_SPIN_FIFO_DATA_0_1
    4'b 1111, // index[63] LAGD_CORE_SPIN_FIFO_DATA_0_2
    4'b 1111, // index[64] LAGD_CORE_SPIN_FIFO_DATA_0_3
    4'b 1111, // index[65] LAGD_CORE_SPIN_FIFO_DATA_1_0
    4'b 1111, // index[66] LAGD_CORE_SPIN_FIFO_DATA_1_1
    4'b 1111, // index[67] LAGD_CORE_SPIN_FIFO_DATA_1_2
    4'b 1111, // index[68] LAGD_CORE_SPIN_FIFO_DATA_1_3
    4'b 1111, // index[69] LAGD_CORE_DEBUG_J_READ_DATA_0
    4'b 1111, // index[70] LAGD_CORE_DEBUG_J_READ_DATA_1
    4'b 1111, // index[71] LAGD_CORE_DEBUG_J_READ_DATA_2
    4'b 1111, // index[72] LAGD_CORE_DEBUG_J_READ_DATA_3
    4'b 1111, // index[73] LAGD_CORE_DEBUG_J_READ_DATA_4
    4'b 1111, // index[74] LAGD_CORE_DEBUG_J_READ_DATA_5
    4'b 1111, // index[75] LAGD_CORE_DEBUG_J_READ_DATA_6
    4'b 1111, // index[76] LAGD_CORE_DEBUG_J_READ_DATA_7
    4'b 1111, // index[77] LAGD_CORE_DEBUG_J_READ_DATA_8
    4'b 1111, // index[78] LAGD_CORE_DEBUG_J_READ_DATA_9
    4'b 1111, // index[79] LAGD_CORE_DEBUG_J_READ_DATA_10
    4'b 1111, // index[80] LAGD_CORE_DEBUG_J_READ_DATA_11
    4'b 1111, // index[81] LAGD_CORE_DEBUG_J_READ_DATA_12
    4'b 1111, // index[82] LAGD_CORE_DEBUG_J_READ_DATA_13
    4'b 1111, // index[83] LAGD_CORE_DEBUG_J_READ_DATA_14
    4'b 1111  // index[84] LAGD_CORE_DEBUG_J_READ_DATA_15
  };

endpackage

