#!/usr/bin/env python3
# Copyright 2025 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
# Author: Jiacong Sun <jiacong.sun@kuleuven.be>
#
# Converts sw/tests/data/clusters_1 and clusters_2 into a C header for bare-metal use.
#
# Output: sw/include/model_f_data.h
#   - model_f_data[4096]  : 1024 256-bit flip candidate vectors, interleaved from
#                            clusters_1 (even indices) and clusters_2 (odd indices),
#                            each packed as 4 x uint64_t.
#                            Last bit of source line -> bit 0 of word[0] (lowest address).

import argparse
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_FILE_1 = os.path.join(SCRIPT_DIR, "clusters_1")
INPUT_FILE_2 = os.path.join(SCRIPT_DIR, "clusters_2")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "..", "..", "include", "model_f_data.h")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate sw/include/model_f_data.h from sw/tests/data/clusters_1 and clusters_2."
    )
    parser.add_argument(
        "--core-onload",
        type=int,
        default=1,
        help="Core index for the J data section name (default: 1).",
    )
    return parser.parse_args()


args = parse_args()
core_onload = args.core_onload

# --- Constants ---
NUM_CLUSTERS = 512          # usable vectors per file (line 1 is skipped)
VEC_BITS = 256          # bits per vector
WORDS_PER_VEC = VEC_BITS // 64   # uint64_t words per vector (= 4)
TOTAL_VECS = NUM_CLUSTERS * 2  # interleaved from 2 files (= 1024)
F_LEN = TOTAL_VECS * WORDS_PER_VEC  # total uint64_t words (= 4096)


def parse_clusters(path):
    with open(path, 'r') as f:
        lines = f.readlines()
    assert len(lines) >= NUM_CLUSTERS + 1, \
        f"{path}: expected at least {NUM_CLUSTERS + 1} lines, got {len(lines)}"
    vecs = []
    for i in range(NUM_CLUSTERS):
        line = lines[1 + i].strip()
        assert len(line) == VEC_BITS, \
            f"{path} line {2 + i}: expected {VEC_BITS} chars, got {len(line)}"
        # Pack as 4 x uint64_t:
        #   word[0]: last  64 chars of line -> last bit = bit 0 (lowest address)
        #   word[3]: first 64 chars of line -> first bit = bit 63 of word[3] (highest address)
        words = [
            int(line[192:256], 2),   # bits  63:0
            int(line[128:192], 2),   # bits 127:64
            int(line[64:128],  2),   # bits 191:128
            int(line[0:64],    2),   # bits 255:192
        ]
        vecs.append(words)
    return vecs


vecs_1 = parse_clusters(INPUT_FILE_1)
vecs_2 = parse_clusters(INPUT_FILE_2)

# Interleave: [c1[0], c2[0], c1[1], c2[1], ...]
f_u64 = []
for i in range(NUM_CLUSTERS):
    f_u64.extend(vecs_1[i])
    f_u64.extend(vecs_2[i])

assert len(f_u64) == F_LEN, f"Expected {F_LEN} uint64_t, got {len(f_u64)}"

# --- Write header ---
with open(OUTPUT_FILE, 'w') as f:
    f.write("// Auto-generated by gen_flip_data.py - do not edit\n")
    f.write("// Sources: sw/tests/data/clusters_1, sw/tests/data/clusters_2\n")
    f.write("// Copyright 2025 KU Leuven.\n")
    f.write("// Licensed under the Apache License, Version 2.0, see LICENSE for details.\n")
    f.write("// SPDX-License-Identifier: Apache-2.0\n")
    f.write("\n")
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n")
    f.write("\n")
    f.write(f"// Flip candidate vectors: {TOTAL_VECS} x {VEC_BITS}-bit vectors,\n")
    f.write("// interleaved from clusters_1 (even indices) and clusters_2 (odd indices).\n")
    f.write(f"// Each vector = {WORDS_PER_VEC} x uint64_t;"
            " last bit of source line is bit 0 of word[0].\n")
    f.write(f"#define MODEL_F_VECS {TOTAL_VECS}"
            f"  // total number of vectors ({NUM_CLUSTERS} per file x 2)\n")
    f.write(f"#define MODEL_F_LEN  {F_LEN}"
            f"  // {TOTAL_VECS}*{WORDS_PER_VEC} uint64_t = {F_LEN * 8 // 1024}KB\n")
    f.write("static const uint64_t model_f_data[MODEL_F_LEN]"
            f" __attribute__((used, section(\".l1f_data_c{core_onload}\"))) = {{\n")
    for i, v in enumerate(f_u64):
        if i % 8 == 0:
            f.write("    ")
        f.write(f"0x{v:016x}")
        if i < F_LEN - 1:
            f.write(", ")
        if i % 8 == 7:
            f.write("\n")
    f.write("\n};\n")

print(f"Generated {OUTPUT_FILE}")
print(f"  Flip data : {TOTAL_VECS} vectors x {VEC_BITS} bits"
      f" ({F_LEN} uint64_t = {F_LEN * 8 // 1024} KB)")
print(f"  clusters_1: {NUM_CLUSTERS} vectors")
print(f"  clusters_2: {NUM_CLUSTERS} vectors")
