#!/usr/bin/env python3
# Copyright 2025 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
# Author: Jiacong Sun <jiacong.sun@kuleuven.be>
#
# Converts sw/tests/data/states_in_1 and states_in_2 into a C header for bare-metal use.
#
# Output: sw/include/spin_data.h
#   - spin_initial_0[8] : initial spin state from states_in_1 (line 1), packed as 8 x uint32_t
#   - spin_initial_1[8] : initial spin state from states_in_2 (line 1), packed as 8 x uint32_t
#   - spin_ref_0[8]     : reference result from states_in_1 (last line), for later comparison
#   - spin_ref_1[8]     : reference result from states_in_2 (last line), for later comparison
#
# Bit ordering per vector:
#   last char of line  -> bit 0  of word[0] -> CONFIG_SPIN_INITIAL_*_0_REG_OFFSET
#   first char of line -> bit 31 of word[7] -> CONFIG_SPIN_INITIAL_*_7_REG_OFFSET

import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_FILE_1 = os.path.join(SCRIPT_DIR, "states_in_1")
INPUT_FILE_2 = os.path.join(SCRIPT_DIR, "states_in_2")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "..", "..", "include", "spin_data.h")

VEC_BITS = 256
WORDS_PER_VEC = VEC_BITS // 32  # 8 x uint32_t per vector


def pack_256bit(line, context):
    """Pack a 256-char binary string into 8 x uint32_t.
    word[k] = int(line[256-32*(k+1) : 256-32*k], 2)
    word[0] <- last  32 chars (bits  31: 0) -> _0_REG_OFFSET
    word[7] <- first 32 chars (bits 255:224) -> _7_REG_OFFSET
    """
    assert len(line) == VEC_BITS, \
        f"{context}: expected {VEC_BITS} chars, got {len(line)}"
    return [
        int(line[VEC_BITS - 32 * (k + 1):VEC_BITS - 32 * k], 2)
        for k in range(WORDS_PER_VEC)
    ]


def parse_state_file(path):
    """Return (initial_words, ref_words): first and last non-empty lines packed."""
    with open(path, 'r') as f:
        lines = [line.strip() for line in f if line.strip()]
    assert len(lines) >= 1, f"{path}: file is empty"
    initial = pack_256bit(lines[0],  f"{path} line 1")
    ref = pack_256bit(lines[-1], f"{path} last line")
    return initial, ref


initial_0, ref_0 = parse_state_file(INPUT_FILE_1)
initial_1, ref_1 = parse_state_file(INPUT_FILE_2)


def fmt_array(name, words):
    vals = ", ".join(f"0x{w:08x}U" for w in words)
    return f"static const uint32_t {name}[{WORDS_PER_VEC}] = {{{vals}}};\n"


with open(OUTPUT_FILE, 'w') as f:
    f.write("// Auto-generated by gen_spin_data.py — do not edit\n")
    f.write("// Sources: sw/tests/data/states_in_1, sw/tests/data/states_in_2\n")
    f.write("// Copyright 2025 KU Leuven.\n")
    f.write("// Licensed under the Apache License, Version 2.0, see LICENSE for details.\n")
    f.write("// SPDX-License-Identifier: Apache-2.0\n")
    f.write("\n")
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n")
    f.write("\n")
    f.write("// Spin initial states and reference results: 256-bit vectors as 8 x uint32_t.\n")
    f.write("// word[0] holds bits  31:0   (last  32 chars of source line) -> _0_REG_OFFSET\n")
    f.write("// word[7] holds bits 255:224 (first 32 chars of source line) -> _7_REG_OFFSET\n")
    f.write("\n")
    f.write("// Initial spin set 0 (states_in_1 line 1) -> CONFIG_SPIN_INITIAL_0_*\n")
    f.write(fmt_array("spin_initial_0", initial_0))
    f.write("\n")
    f.write("// Initial spin set 1 (states_in_2 line 1) -> CONFIG_SPIN_INITIAL_1_*\n")
    f.write(fmt_array("spin_initial_1", initial_1))
    f.write("\n")
    f.write("// Reference result 0 (states_in_1 last line, reserved for later comparison)\n")
    f.write(fmt_array("spin_ref_0", ref_0))
    f.write("\n")
    f.write("// Reference result 1 (states_in_2 last line, reserved for later comparison)\n")
    f.write(fmt_array("spin_ref_1", ref_1))

print(f"Generated {OUTPUT_FILE}")
print(f"  spin_initial_0 : {['0x%08x' % w for w in initial_0]}")
print(f"  spin_initial_1 : {['0x%08x' % w for w in initial_1]}")
print(f"  spin_ref_0     : {['0x%08x' % w for w in ref_0]}")
print(f"  spin_ref_1     : {['0x%08x' % w for w in ref_1]}")
