# Copyright 2026 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Jiacong Sun <jiacong.sun@kuleuven.be>

# This script is used for vcs, which parses the Tcl vlog script generated by bender to extract either the list of HDL files or the include directories.

import argparse
import os
import re


def parse_args():
    parser = argparse.ArgumentParser(description="Parse bender-generated Tcl vlog script")
    parser.add_argument("-f", "--file", required=True, help="Path to bender Tcl script")
    parser.add_argument(
        "-t",
        "--target",
        required=True,
        choices=["HDL_FILES", "INCLUDE_DIRS"],
        help="Output target type",
    )
    parser.add_argument(
        "--raw",
        action="store_true",
        help="For INCLUDE_DIRS: return directories directly instead of enumerating header files",
    )
    return parser.parse_args()


def unique_keep_order(items):
    seen = set()
    out = []
    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def main():
    args = parse_args()

    with open(args.file, "r", encoding="utf-8") as f:
        content = f.read()

    root_match = re.search(r'^set\s+ROOT\s+"([^"]+)"', content, flags=re.MULTILINE)
    root = root_match.group(1) if root_match else ""

    tokens = re.findall(r'"([^"]+)"', content)

    if args.target == "HDL_FILES":
        exts = (".sv", ".svh", ".v", ".vh")
        files = []
        for token in tokens:
            if token.startswith("+incdir+") or token.startswith("+define+"):
                continue
            if token.endswith(exts):
                path = token.replace("$ROOT", root)
                files.append(path)
        print(" ".join(unique_keep_order(files)))
        return

    include_dirs = []
    for token in tokens:
        if token.startswith("+incdir+"):
            inc = token[len("+incdir+") :].replace("$ROOT", root)
            include_dirs.append(inc)

    include_dirs = unique_keep_order(include_dirs)

    if args.raw:
        print(" ".join(include_dirs))
        return

    headers = []
    for inc_dir in include_dirs:
        if os.path.isdir(inc_dir):
            for walk_root, _, files in os.walk(inc_dir):
                for file_name in files:
                    if file_name.endswith(".vh") or file_name.endswith(".svh"):
                        headers.append(os.path.join(walk_root, file_name))

    print(" ".join(unique_keep_order(headers)))


if __name__ == "__main__":
    main()
