# Copyright 2025 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

PROJECT_ROOT ?= $(abspath $(CURDIR)/../../../)
DEFINES += PROJECT_ROOT=$(PROJECT_ROOT)/ # for galena behavior model

include ../common.mk
